spring:
  datasource:
    # Cadena de conexión estándar para PostgreSQL
    url: jdbc:postgresql://localhost:45001/Construction3D
    username: model3d
    password: pass123
    driver-class-name: org.postgresql.Driver
    
    # Configuración de HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 'update' crea o actualiza las tablas automáticamente según tus clases Java
      ddl-auto: create
    show-sql: true
    properties:
        hibernate:
            format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always